/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EulaRouteImport } from './routes/eula'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProSuccessRouteImport } from './routes/pro.success'
import { Route as AuthenticatedShiftsRouteImport } from './routes/_authenticated.shifts'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedMoreRouteImport } from './routes/_authenticated.more'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated.calendar'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'
import { Route as ApiPublicHooksSendWeeklyReminderRouteImport } from './routes/api/public/hooks/send-weekly-reminder'
import { Route as ApiPublicHooksSendTrialRemindersRouteImport } from './routes/api/public/hooks/send-trial-reminders'
import { Route as ApiPublicHooksSendPushWeeklyReminderRouteImport } from './routes/api/public/hooks/send-push-weekly-reminder'
import { Route as ApiPublicHooksSendPushNotificationRouteImport } from './routes/api/public/hooks/send-push-notification'
import { Route as ApiPublicHooksSendPushDailyReminderRouteImport } from './routes/api/public/hooks/send-push-daily-reminder'
import { Route as ApiPublicHooksSendDailyReminderRouteImport } from './routes/api/public/hooks/send-daily-reminder'
import { Route as ApiPublicHooksDispatchShiftAlertsRouteImport } from './routes/api/public/hooks/dispatch-shift-alerts'
import { Route as ApiPublicGoogleSyncAllRouteImport } from './routes/api/public/google/sync-all'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EulaRoute = EulaRouteImport.update({
  id: '/eula',
  path: '/eula',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSuccessRoute = ProSuccessRouteImport.update({
  id: '/pro/success',
  path: '/pro/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShiftsRoute = AuthenticatedShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMoreRoute = AuthenticatedMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendWeeklyReminderRoute =
  ApiPublicHooksSendWeeklyReminderRouteImport.update({
    id: '/api/public/hooks/send-weekly-reminder',
    path: '/api/public/hooks/send-weekly-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendTrialRemindersRoute =
  ApiPublicHooksSendTrialRemindersRouteImport.update({
    id: '/api/public/hooks/send-trial-reminders',
    path: '/api/public/hooks/send-trial-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendPushWeeklyReminderRoute =
  ApiPublicHooksSendPushWeeklyReminderRouteImport.update({
    id: '/api/public/hooks/send-push-weekly-reminder',
    path: '/api/public/hooks/send-push-weekly-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendPushNotificationRoute =
  ApiPublicHooksSendPushNotificationRouteImport.update({
    id: '/api/public/hooks/send-push-notification',
    path: '/api/public/hooks/send-push-notification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendPushDailyReminderRoute =
  ApiPublicHooksSendPushDailyReminderRouteImport.update({
    id: '/api/public/hooks/send-push-daily-reminder',
    path: '/api/public/hooks/send-push-daily-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendDailyReminderRoute =
  ApiPublicHooksSendDailyReminderRouteImport.update({
    id: '/api/public/hooks/send-daily-reminder',
    path: '/api/public/hooks/send-daily-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchShiftAlertsRoute =
  ApiPublicHooksDispatchShiftAlertsRouteImport.update({
    id: '/api/public/hooks/dispatch-shift-alerts',
    path: '/api/public/hooks/dispatch-shift-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleSyncAllRoute = ApiPublicGoogleSyncAllRouteImport.update({
  id: '/api/public/google/sync-all',
  path: '/api/public/google/sync-all',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eula': typeof EulaRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/more': typeof AuthenticatedMoreRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/pro/success': typeof ProSuccessRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/api/public/google/sync-all': typeof ApiPublicGoogleSyncAllRoute
  '/api/public/hooks/dispatch-shift-alerts': typeof ApiPublicHooksDispatchShiftAlertsRoute
  '/api/public/hooks/send-daily-reminder': typeof ApiPublicHooksSendDailyReminderRoute
  '/api/public/hooks/send-push-daily-reminder': typeof ApiPublicHooksSendPushDailyReminderRoute
  '/api/public/hooks/send-push-notification': typeof ApiPublicHooksSendPushNotificationRoute
  '/api/public/hooks/send-push-weekly-reminder': typeof ApiPublicHooksSendPushWeeklyReminderRoute
  '/api/public/hooks/send-trial-reminders': typeof ApiPublicHooksSendTrialRemindersRoute
  '/api/public/hooks/send-weekly-reminder': typeof ApiPublicHooksSendWeeklyReminderRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eula': typeof EulaRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/more': typeof AuthenticatedMoreRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/pro/success': typeof ProSuccessRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/api/public/google/sync-all': typeof ApiPublicGoogleSyncAllRoute
  '/api/public/hooks/dispatch-shift-alerts': typeof ApiPublicHooksDispatchShiftAlertsRoute
  '/api/public/hooks/send-daily-reminder': typeof ApiPublicHooksSendDailyReminderRoute
  '/api/public/hooks/send-push-daily-reminder': typeof ApiPublicHooksSendPushDailyReminderRoute
  '/api/public/hooks/send-push-notification': typeof ApiPublicHooksSendPushNotificationRoute
  '/api/public/hooks/send-push-weekly-reminder': typeof ApiPublicHooksSendPushWeeklyReminderRoute
  '/api/public/hooks/send-trial-reminders': typeof ApiPublicHooksSendTrialRemindersRoute
  '/api/public/hooks/send-weekly-reminder': typeof ApiPublicHooksSendWeeklyReminderRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/eula': typeof EulaRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/more': typeof AuthenticatedMoreRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shifts': typeof AuthenticatedShiftsRoute
  '/pro/success': typeof ProSuccessRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/api/public/google/sync-all': typeof ApiPublicGoogleSyncAllRoute
  '/api/public/hooks/dispatch-shift-alerts': typeof ApiPublicHooksDispatchShiftAlertsRoute
  '/api/public/hooks/send-daily-reminder': typeof ApiPublicHooksSendDailyReminderRoute
  '/api/public/hooks/send-push-daily-reminder': typeof ApiPublicHooksSendPushDailyReminderRoute
  '/api/public/hooks/send-push-notification': typeof ApiPublicHooksSendPushNotificationRoute
  '/api/public/hooks/send-push-weekly-reminder': typeof ApiPublicHooksSendPushWeeklyReminderRoute
  '/api/public/hooks/send-trial-reminders': typeof ApiPublicHooksSendTrialRemindersRoute
  '/api/public/hooks/send-weekly-reminder': typeof ApiPublicHooksSendWeeklyReminderRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eula'
    | '/login'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/calendar'
    | '/dashboard'
    | '/more'
    | '/onboarding'
    | '/settings'
    | '/shifts'
    | '/pro/success'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/auth/google/callback'
    | '/api/public/google/sync-all'
    | '/api/public/hooks/dispatch-shift-alerts'
    | '/api/public/hooks/send-daily-reminder'
    | '/api/public/hooks/send-push-daily-reminder'
    | '/api/public/hooks/send-push-notification'
    | '/api/public/hooks/send-push-weekly-reminder'
    | '/api/public/hooks/send-trial-reminders'
    | '/api/public/hooks/send-weekly-reminder'
    | '/api/public/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eula'
    | '/login'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/calendar'
    | '/dashboard'
    | '/more'
    | '/onboarding'
    | '/settings'
    | '/shifts'
    | '/pro/success'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/auth/google/callback'
    | '/api/public/google/sync-all'
    | '/api/public/hooks/dispatch-shift-alerts'
    | '/api/public/hooks/send-daily-reminder'
    | '/api/public/hooks/send-push-daily-reminder'
    | '/api/public/hooks/send-push-notification'
    | '/api/public/hooks/send-push-weekly-reminder'
    | '/api/public/hooks/send-trial-reminders'
    | '/api/public/hooks/send-weekly-reminder'
    | '/api/public/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/eula'
    | '/login'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/more'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/shifts'
    | '/pro/success'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/auth/google/callback'
    | '/api/public/google/sync-all'
    | '/api/public/hooks/dispatch-shift-alerts'
    | '/api/public/hooks/send-daily-reminder'
    | '/api/public/hooks/send-push-daily-reminder'
    | '/api/public/hooks/send-push-notification'
    | '/api/public/hooks/send-push-weekly-reminder'
    | '/api/public/hooks/send-trial-reminders'
    | '/api/public/hooks/send-weekly-reminder'
    | '/api/public/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  EulaRoute: typeof EulaRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ProSuccessRoute: typeof ProSuccessRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  ApiPublicGoogleSyncAllRoute: typeof ApiPublicGoogleSyncAllRoute
  ApiPublicHooksDispatchShiftAlertsRoute: typeof ApiPublicHooksDispatchShiftAlertsRoute
  ApiPublicHooksSendDailyReminderRoute: typeof ApiPublicHooksSendDailyReminderRoute
  ApiPublicHooksSendPushDailyReminderRoute: typeof ApiPublicHooksSendPushDailyReminderRoute
  ApiPublicHooksSendPushNotificationRoute: typeof ApiPublicHooksSendPushNotificationRoute
  ApiPublicHooksSendPushWeeklyReminderRoute: typeof ApiPublicHooksSendPushWeeklyReminderRoute
  ApiPublicHooksSendTrialRemindersRoute: typeof ApiPublicHooksSendTrialRemindersRoute
  ApiPublicHooksSendWeeklyReminderRoute: typeof ApiPublicHooksSendWeeklyReminderRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eula': {
      id: '/eula'
      path: '/eula'
      fullPath: '/eula'
      preLoaderRoute: typeof EulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/success': {
      id: '/pro/success'
      path: '/pro/success'
      fullPath: '/pro/success'
      preLoaderRoute: typeof ProSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/shifts': {
      id: '/_authenticated/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthenticatedShiftsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/more': {
      id: '/_authenticated/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AuthenticatedMoreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-weekly-reminder': {
      id: '/api/public/hooks/send-weekly-reminder'
      path: '/api/public/hooks/send-weekly-reminder'
      fullPath: '/api/public/hooks/send-weekly-reminder'
      preLoaderRoute: typeof ApiPublicHooksSendWeeklyReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-trial-reminders': {
      id: '/api/public/hooks/send-trial-reminders'
      path: '/api/public/hooks/send-trial-reminders'
      fullPath: '/api/public/hooks/send-trial-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendTrialRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-push-weekly-reminder': {
      id: '/api/public/hooks/send-push-weekly-reminder'
      path: '/api/public/hooks/send-push-weekly-reminder'
      fullPath: '/api/public/hooks/send-push-weekly-reminder'
      preLoaderRoute: typeof ApiPublicHooksSendPushWeeklyReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-push-notification': {
      id: '/api/public/hooks/send-push-notification'
      path: '/api/public/hooks/send-push-notification'
      fullPath: '/api/public/hooks/send-push-notification'
      preLoaderRoute: typeof ApiPublicHooksSendPushNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-push-daily-reminder': {
      id: '/api/public/hooks/send-push-daily-reminder'
      path: '/api/public/hooks/send-push-daily-reminder'
      fullPath: '/api/public/hooks/send-push-daily-reminder'
      preLoaderRoute: typeof ApiPublicHooksSendPushDailyReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-daily-reminder': {
      id: '/api/public/hooks/send-daily-reminder'
      path: '/api/public/hooks/send-daily-reminder'
      fullPath: '/api/public/hooks/send-daily-reminder'
      preLoaderRoute: typeof ApiPublicHooksSendDailyReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-shift-alerts': {
      id: '/api/public/hooks/dispatch-shift-alerts'
      path: '/api/public/hooks/dispatch-shift-alerts'
      fullPath: '/api/public/hooks/dispatch-shift-alerts'
      preLoaderRoute: typeof ApiPublicHooksDispatchShiftAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/sync-all': {
      id: '/api/public/google/sync-all'
      path: '/api/public/google/sync-all'
      fullPath: '/api/public/google/sync-all'
      preLoaderRoute: typeof ApiPublicGoogleSyncAllRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMoreRoute: typeof AuthenticatedMoreRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShiftsRoute: typeof AuthenticatedShiftsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMoreRoute: AuthenticatedMoreRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShiftsRoute: AuthenticatedShiftsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  EulaRoute: EulaRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ProSuccessRoute: ProSuccessRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  ApiPublicGoogleSyncAllRoute: ApiPublicGoogleSyncAllRoute,
  ApiPublicHooksDispatchShiftAlertsRoute:
    ApiPublicHooksDispatchShiftAlertsRoute,
  ApiPublicHooksSendDailyReminderRoute: ApiPublicHooksSendDailyReminderRoute,
  ApiPublicHooksSendPushDailyReminderRoute:
    ApiPublicHooksSendPushDailyReminderRoute,
  ApiPublicHooksSendPushNotificationRoute:
    ApiPublicHooksSendPushNotificationRoute,
  ApiPublicHooksSendPushWeeklyReminderRoute:
    ApiPublicHooksSendPushWeeklyReminderRoute,
  ApiPublicHooksSendTrialRemindersRoute: ApiPublicHooksSendTrialRemindersRoute,
  ApiPublicHooksSendWeeklyReminderRoute: ApiPublicHooksSendWeeklyReminderRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
